/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2017-06-16.892d4a0"
#define SSHVER "PuTTY-Snapshot-2017-06-16.892d4a0"
#define BINARY_VERSION 0,69,1053,0
#define SOURCE_COMMIT "892d4a0188ffd8aa60dc11b4bace30dfb0f9d50e"
